#!/usr/bin/env python3
from pathlib import Path

p = Path("src/optical_flow_mavlink.cpp")
s = p.read_text()

old = '''        // WORKED 5% closure estimator for Web UI / HOME return.\n        // The estimator itself is frozen in worked5_estimator.hpp.  This layer\n        // only maps its metric camera-plane delta into the existing N/E HOME\n        // coordinate system.  The ArduPilot OPTICAL_FLOW publisher above is\n        // intentionally untouched and remains an independent comparison path.\n        web_raw_step_valid=false;\n        web_raw_vn=web_raw_ve=0.0;\n        if(s.valid && fg_ok && dt>0.0 && dt<0.2){\n          double hcam=0.0;\n          if(bench_true_camera_height>0.0){\n            hcam=bench_true_camera_height;\n          } else if(current_camera_height_valid){\n            hcam=current_camera_height_m;\n          }\n          if(hcam>0.02 && std::isfinite(hcam)){\n            const auto w5=worked5::estimate(\n              s.metric_prev_points,s.metric_curr_points,\n              calib.K,focal_scale,calib.D,hcam,dt);\n            if(w5.valid){\n              // Frozen blind convention gives a metric displacement in the\n              // camera/body horizontal plane: X=+dv*H, Y=-du*H.  Rotate that\n              // already-metric delta into NED using the FC attitude.  No extra\n              // empirical scale, axis correction or gyro subtraction is added.\n              const double cr=std::cos(fg.roll),  sr=std::sin(fg.roll);\n              const double cp=std::cos(fg.pitch), sp=std::sin(fg.pitch);\n              const double cy=std::cos(fg.yaw),   sy=std::sin(fg.yaw);\n              const double r00=cy*cp;\n              const double r01=cy*sp*sr-sy*cr;\n              const double r10=sy*cp;\n              const double r11=sy*sp*sr+cy*cr;\n\n              const double dN=r00*w5.dx_m + r01*w5.dy_m;\n              const double dE=r10*w5.dx_m + r11*w5.dy_m;\n              web_raw_n += dN;\n              web_raw_e += dE;\n              web_raw_vn=dN/dt;\n              web_raw_ve=dE/dt;\n              web_raw_step_valid=true;\n            }\n          }\n        }\n'''
new = '''        // WORKED 5% closure estimator for Web UI / HOME return.\n        // The estimator itself is frozen in worked5_estimator.hpp.  This layer\n        // only maps its metric camera-plane delta into the existing N/E HOME\n        // coordinate system.  The ArduPilot OPTICAL_FLOW publisher above is\n        // intentionally untouched and remains an independent comparison path.\n        // Per-frame forensic values below are logging only; they do not feed FC.\n        bool worked5_diag_valid=false;\n        int worked5_diag_points=0;\n        double worked5_diag_hcam=0.0;\n        double worked5_diag_du_norm=0.0,worked5_diag_dv_norm=0.0;\n        double worked5_diag_dx=0.0,worked5_diag_dy=0.0;\n        double worked5_diag_dN=0.0,worked5_diag_dE=0.0;\n        web_raw_step_valid=false;\n        web_raw_vn=web_raw_ve=0.0;\n        if(s.valid && fg_ok && dt>0.0 && dt<0.2){\n          double hcam=0.0;\n          if(bench_true_camera_height>0.0){\n            hcam=bench_true_camera_height;\n          } else if(current_camera_height_valid){\n            hcam=current_camera_height_m;\n          }\n          worked5_diag_hcam=hcam;\n          if(hcam>0.02 && std::isfinite(hcam)){\n            worked5_diag_points=(int)std::min(s.metric_prev_points.size(),s.metric_curr_points.size());\n            const auto w5=worked5::estimate(\n              s.metric_prev_points,s.metric_curr_points,\n              calib.K,focal_scale,calib.D,hcam,dt);\n            worked5_diag_du_norm=w5.du_norm;\n            worked5_diag_dv_norm=w5.dv_norm;\n            worked5_diag_dx=w5.dx_m;\n            worked5_diag_dy=w5.dy_m;\n            if(w5.valid){\n              // Frozen blind convention gives a metric displacement in the\n              // camera/body horizontal plane: X=+dv*H, Y=-du*H.  Rotate that\n              // already-metric delta into NED using the FC attitude.  No extra\n              // empirical scale, axis correction or gyro subtraction is added.\n              const double cr=std::cos(fg.roll),  sr=std::sin(fg.roll);\n              const double cp=std::cos(fg.pitch), sp=std::sin(fg.pitch);\n              const double cy=std::cos(fg.yaw),   sy=std::sin(fg.yaw);\n              const double r00=cy*cp;\n              const double r01=cy*sp*sr-sy*cr;\n              const double r10=sy*cp;\n              const double r11=sy*sp*sr+cy*cr;\n\n              const double dN=r00*w5.dx_m + r01*w5.dy_m;\n              const double dE=r10*w5.dx_m + r11*w5.dy_m;\n              worked5_diag_valid=true;\n              worked5_diag_dN=dN;\n              worked5_diag_dE=dE;\n              web_raw_n += dN;\n              web_raw_e += dE;\n              web_raw_vn=dN/dt;\n              web_raw_ve=dE/dt;\n              web_raw_step_valid=true;\n            }\n          }\n        }\n'''
if old not in s:
    raise SystemExit("ERROR: WORKED5 integration block not found; source differs from expected baseline")
s = s.replace(old, new, 1)

old_header = 'ekf_compass_var,ekf_terrain_var,return_event,fc_roll'
new_header = ('ekf_compass_var,ekf_terrain_var,return_event,rc_zero_seq,'
              'worked5_valid,worked5_points,worked5_hcam_m,worked5_du_norm,worked5_dv_norm,'
              'worked5_dx_m,worked5_dy_m,worked5_dN_m,worked5_dE_m,worked5_acc_n_m,worked5_acc_e_m,fc_roll')
if old_header not in s:
    raise SystemExit("ERROR: CSV header anchor not found")
s = s.replace(old_header, new_header, 1)

old_row = '''           <<pending_return_event<<','\n           <<(fg_ok?fg.roll:0.0)<<','''
new_row = '''           <<pending_return_event<<','\n           <<rc_zero_seq<<','\n           <<(worked5_diag_valid?1:0)<<','<<worked5_diag_points<<','<<worked5_diag_hcam<<','\n           <<worked5_diag_du_norm<<','<<worked5_diag_dv_norm<<','\n           <<worked5_diag_dx<<','<<worked5_diag_dy<<','<<worked5_diag_dN<<','<<worked5_diag_dE<<','\n           <<web_raw_n<<','<<web_raw_e<<','\n           <<(fg_ok?fg.roll:0.0)<<','''
if old_row not in s:
    raise SystemExit("ERROR: CSV row anchor not found")
s = s.replace(old_row, new_row, 1)

p.write_text(s)
print("OK: WORKED5 online forensic columns added to src/optical_flow_mavlink.cpp")
print("Frozen estimator and ArduPilot publisher were not changed.")
